name: repository-dispatch-caller
description: https://github.com/champ-oss/action-repository-dispatch-caller

  GITHUB_TOKEN=${1?github token is required}
  EVENT=${2?event is required}
  ORG_NAME=${3?org name is required}
  REPO_NAME=${4?repo name is required}

inputs:
  GITHUB_TOKEN:
    description: 'github token used to run action'
    required: true
  EVENT:
    description: 'event call'
    required: true
  ORG_NAME:
    description: 'org name'
    required: true
  REPO_NAME:
    description: 'repo name'
    required: true
  GITHUB_REF:
    description: 'github ref'
    required: true
  GITHUB_SHA:
    description: 'github sha'
    required: true
runs:
  using: "composite"
  steps:
    - name: run python script
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        EVENT: ${{ inputs.EVENT }}
        ORG_NAME: ${{ inputs.ORG_NAME }}
        REPO_NAME: ${{ inputs.REPO_NAME }}
        GITHUB_REF: ${{ inputs.GITHUB_REF }}
        GITHUB_SHA: ${{ inputs.GITHUB_SHA }}
      run: |
        python ${GITHUB_ACTION_PATH}/action-repository-dispatch-caller.py